print('*'*50)
name = input('请输入姓名：')
sex = input('请输入性别：')
phone = input('请输入电话：')
addr = input('请输入家庭住址：')
email = input('请输入邮箱号码：')
print('*'*50)
print('姓名%s\n性别%s\n电话%s\n住址%s\n邮箱号码%s\n'%(name,sex,phone,addr,email))
print('*'*50)
