print('*'*50)
name = input('请输入您的姓名：')
age = int(input('请输入您的年龄：'))
sex = input('请输入您的性别：')
weight = float(input('请输入您的体重：'))
height = float(input('请输入您的身高：'))
Id_number = int(input('请输入您的身份证号码：'))
addr = input('请输入您的地址：')
phone = int(input('请输入您的手机电话：'))
case = input('请输入您的职位：')
tel = int(input('请输入您的电话：'))
money = float(input('请输入您的薪水：'))
birthday = input('请输入您的出生日期：')
print('*'*50)
print('姓名%s\n年龄%d\n性别%s\n体重%.02f\n身高%.02f\n身份证号码%d\n地址%s\n手机号码%s\n职位%s\n电话%s\n薪水%.02f\n出生日期%s'%(name,age,sex,weight,height,Id_number,addr,phone,case,tel,money,birthday))
print('*'*50)
