print('%'*50)
print('房屋销售系统')
print('_'*25)
account = input('请输入您的账号')
password = input('请输入您的密码')
print('_'*25)
size = input('房屋大小：')
size1 =  float(input('房子面积：'))
where = input('所在城市：')
where1 = input('详细位置：')
price = float(input('价格：'))
name = input('购房顾问：')
print('_'*25)
print('账号：%s\n密码：%s\n房屋大小%s\n面积：%.02f\n所在城市：%s\n详细位置:%s\n价格：%.02f\n顾问：%s'%(account,password,size,size1,where,where1,price,name))
